version: '3.1'

services:

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: test123

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 9913:8080

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "9912:80"
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx

networks:
  default:
    name: node-services
